name: push_nuget

# on push on master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@master
    
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - run: dotnet build --configuration Release
      working-directory: src

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: Publish VL Nuget
      uses: vvvv/PublishVLNuget@1.0.40
      with:
        nuspec: deployment\VL.OpenEXR.nuspec
        icon-src: https://raw.githubusercontent.com/vvvv/PublicContent/master/nugeticon.png
        icon-dst: ./deployment/nugeticon.png
        nuget-key: ${{ secrets.NUGET_KEY }}